"""
alerts.py
---------

Email alert system for
NER Landslide Early Warning System.

Uses Gmail SMTP.

Run:
    python src/alerts.py
"""

import os
import smtplib

from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

from dotenv import load_dotenv


# ==========================================
# LOAD ENVIRONMENT VARIABLES
# ==========================================

load_dotenv()


EMAIL_ADDRESS = os.getenv(
    "EMAIL_ADDRESS"
)

EMAIL_APP_PASSWORD = os.getenv(
    "EMAIL_APP_PASSWORD"
)


# ==========================================
# CHECK EMAIL CONFIGURATION
# ==========================================

def check_email_config():

    if not EMAIL_ADDRESS:
        return False

    if not EMAIL_APP_PASSWORD:
        return False

    return True


# ==========================================
# SEND EMAIL ALERT
# ==========================================

def send_email_alert(
    receiver_email,
    location,
    risk_score,
    risk_level,
    rainfall_24h,
    rainfall_3d,
    rainfall_7d,
    temperature,
    slope,
    elevation,
    recommendation
):

    # ======================================
    # CHECK CONFIG
    # ======================================

    if not check_email_config():

        return {
            "success": False,
            "message":
                "Email configuration missing."
        }


    # ======================================
    # EMAIL SUBJECT
    # ======================================

    subject = (
        f"🚨 Landslide {risk_level} Alert "
        f"- {location}"
    )


    # ======================================
    # EMAIL BODY
    # ======================================

    body = f"""
NER LANDSLIDE EARLY WARNING SYSTEM

----------------------------------------

Location:
{location}

Risk Score:
{risk_score:.2f}%

Risk Level:
{risk_level}

----------------------------------------

WEATHER CONDITIONS

Rainfall - Last 24 Hours:
{rainfall_24h:.2f} mm

Rainfall - Last 3 Days:
{rainfall_3d:.2f} mm

Rainfall - Last 7 Days:
{rainfall_7d:.2f} mm

Temperature:
{temperature:.2f} °C

----------------------------------------

TERRAIN CONDITIONS

Slope:
{slope:.2f} degrees

Elevation:
{elevation:.2f} metres

----------------------------------------

RECOMMENDED ACTION

{recommendation}

----------------------------------------

This alert was generated by the
NER AI-Based Landslide Early Warning System.

Model-generated risk scores should be
verified with field observations and
official disaster-management procedures.
"""


    # ======================================
    # CREATE MESSAGE
    # ======================================

    message = MIMEMultipart()

    message[
        "From"
    ] = EMAIL_ADDRESS

    message[
        "To"
    ] = receiver_email

    message[
        "Subject"
    ] = subject


    message.attach(
        MIMEText(
            body,
            "plain"
        )
    )


    # ======================================
    # SEND EMAIL
    # ======================================

    try:

        server = smtplib.SMTP(
            "smtp.gmail.com",
            587
        )

        server.starttls()

        server.login(
            EMAIL_ADDRESS,
            EMAIL_APP_PASSWORD
        )

        server.sendmail(
            EMAIL_ADDRESS,
            receiver_email,
            message.as_string()
        )

        server.quit()


        return {
            "success": True,
            "message":
                "Email alert sent successfully."
        }


    except Exception as error:

        return {
            "success": False,
            "message": str(error)
        }


# ==========================================
# TEST EMAIL
# ==========================================

if __name__ == "__main__":

    print(
        "\n======================================"
    )

    print(
        "EMAIL ALERT TEST"
    )

    print(
        "======================================"
    )


    receiver = input(
        "\nEnter receiver email: "
    )


    result = send_email_alert(

        receiver_email=
            receiver,

        location=
            "Haflong, Assam",

        risk_score=
            82.50,

        risk_level=
            "CRITICAL",

        rainfall_24h=
            95,

        rainfall_3d=
            210,

        rainfall_7d=
            410,

        temperature=
            23.5,

        slope=
            38.5,

        elevation=
            680,

        recommendation=(
            "Immediate field inspection is "
            "recommended. Monitor vulnerable "
            "slopes and restrict traffic if "
            "slope movement is observed."
        )
    )


    print(
        "\nResult:"
    )

    print(
        result["message"]
    )